### ISSUE TITLE
No Example??

### ISSUE THREAD

**Issue by vesubramanian** [KJ002/read-yaml#3]
Can you please provide some example of Yaml data and how to consume it? What is Key-Path and what are "runs" and "using"? Very disappointing documentation.

**Comment by KJ002** [comment]
There is example documentation in the README. However let me clarify:

key-path: The path of keys that are to be followed. if "runs" is a key at the most global scope of the file and "using" is a key that is a child of the "runs" key it will follow the path until it reaches the final key and returns the value of the last key. This example can be seen in ‘action.yml‘.

file: The path to the file to read from.

**Comment by vesubramanian** [comment]
So, it cannot parse any YAML structure?

**Comment by KJ002** [comment]
It reads the yaml as key, value pairs. It traverses the data structure and reads down the keys provided. A key may contain a value which is an array of key value pairs or a value or another key value pair but that would be redundant.

**Comment by vesubramanian** [comment]
What I am not able to understand is the Required Input parameter - key-path? What if I want to simply parse the whole yaml file and return an object (which will contain a dictionary or key-value pairs). Why is key-path a Required parameter? Without an example of what a key-path would look like, it is very difficult to understand / use.

**Comment by KJ002** [comment]
This is not the intended functionality of read-yaml, it is simply to return a value from a yaml file be it a string, int or bool.

**Comment by vesubramanian** [comment]
The description is a little misleading. "This action reads yaml data from a file and outputs the result."

**Comment by KJ002** [comment]
You're right, I shall get to changing that at some point.
