### ISSUE TITLE
Issue with values starting with zero

### ISSUE THREAD

**Issue by mliner** [KJ002/read-yaml#4]
Hello there,

we are using this action to read configuration yaml for deployments. If we have a value for key that starts with 0 (zero) it is being removed in the action output. Is there anything that fix that? I am not js guy therefore cannot provide a PR for fix. Thanks in advance.

example:
`accountid: '0123456789'`

**Comment by KJ002** [comment]
Thank you for this issue,

I am quite surprised by this. Could you provide a more in-depth example and output?

**Comment by KJ002** [comment]
After some thinking about this, my thought is that you may be storing the `accountid` as an integer which it would make sense for leading zeros to be removed. Is this the case?
